---
title: "Homework 7"
author: "Sam Brewer"
date: "3/2/2022"
output: html_document
---

# Homework 7

## Question 1
```{r}
library(tidyverse)
str(iris)

```
Observation: 150
Variables: 5

## Question 2
```{r}
iris1 <- data.frame(filter(iris, Species %in% c("virginica","versicolor"), Sepal.Length > 6, Sepal.Width > 2.5))
glimpse(iris1)
```
Observations: 56
Variables: 5

## Question 3
```{r}
iris2 <- data.frame(select(iris1, Species, Sepal.Length, Sepal.Width))
glimpse(iris2)
```
Observations: 56
Variables: 3

## Question 4
```{r}
iris3 <- data.frame(arrange(iris2, by=desc(Sepal.Length)))
head(iris3)

```

## Question 5
```{r}
iris4 <- data.frame(mutate(iris3, Sepal.Area = Sepal.Length*Sepal.Width))
glimpse(iris4)

```
Observations: 56
Variables: 4

## Question 6
```{r}
iris5 <- summarize(iris4, Avg.Sepal.Length = mean(Sepal.Length), Avg.Sepal.Width = mean(Sepal.Width), Sample.Size = n())
print(iris5)

```

## Question 7
```{r}
iris6 <- iris4 %>%
  group_by(Species) %>%
  summarize(Avg.Sepal.Length = mean(Sepal.Length), Avg.Sepal.Width = mean(Sepal.Width), Sample.Size = n())
print(iris6)

```

## Question 8
```{r}
iris %>%
  filter(Species %in% c("virginica","versicolor"), Sepal.Length > 6, Sepal.Width > 2.5) %>%
  select(Species, Sepal.Length, Sepal.Width) %>%
  arrange(by=desc(Sepal.Length)) %>%
  mutate(Sepal.Area = Sepal.Length*Sepal.Width) %>%
  # summarize(Avg.Sepal.Length = mean(Sepal.Length), Avg.Sepal.Width = mean(Sepal.Width), Sample.Size = n()) %>%
  group_by(Species) %>%
  summarize(Avg.Sepal.Length = mean(Sepal.Length), Avg.Sepal.Width = mean(Sepal.Width), Sample.Size = n())

```

## Question 9
```{r}
head(iris)
iris %>%
  pivot_longer(cols= 1:4,
               names_to = "Measure",
               values_to = "Value",
               values_drop_na = T)

```

