---
title: "Homework 4"
author: "Sam Brewer"
date: "2/9/2022"
output: html_document
---

**Question 1**

```{r}
x <- 1.1

a <- 2.2

b <- 3.3

```
**1A**

```{r}
z <- x^{a^b}

print(z)
```
**1B**

```{r}
z <- {x^a}^b

print(z)
```
**1C**

```{r}
z <- 3*x^3 + 2*x^2 + 1

print(z)
```
**Question 2**

**2A**

\phantom{?seq}

\phantom{?rep}

```{r}
line_one <- seq(1,8) # creates 1 to 8 sequence
line_one_repeated <- rep.int(line_one, 2) # repeats the 1 to 8 sequence twice
print(line_one_repeated)
```
**2B**

```{r}
line_two <- rep(1:5, c(1,2,3,4,5)) # to get each number to repeat that same number of times
print(line_two)
```
**2C**

```{r}
line_three <- rep(5:1, c(1,2,3,4,5))
print(line_three)
```

**Question 3**

```{r}
random_vector <- runif(2)
x <- random_vector[1] # grabs first element in random_vector
y <- random_vector[2] # grabs second
radius_squared <- x + y 
radius <- radius_squared^{1/2} # square root of r^2
theta <- atan(y/x) #arc tangent function
print(radius, theta) # polar coordinate

```

**Question 4**

```{r}
queue <- c("sheep", "fox", "owl", "ant")

```

**4A**
\phantom{?append}

```{r}

queue <- append(queue, "serpent", after = length(queue))

```

**4B**
?rm
```{r}

queue <- queue[-1] # indexing

```

**4C**

```{r}

queue <- c("donkey", queue)
```

**4D**

```{r}

queue <- queue[-5]

```

**4E**

```{r}

queue <- queue[-3]

```

**4F**

```{r}

queue <- append(queue, "aphid", after = 2)

```

**4G**

\phantom{?which}

```{r}

aphid_position <- which(queue == "aphid")
print(aphid_position)

```

**Question 5**

\phantom{?seq}

```{r}

hundred_vector <- seq(1, 100)

not_div_vector <- which((hundred_vector %% 2 != 0) & (hundred_vector %% 3 != 0) & (hundred_vector %% 7 != 0))

print(not_div_vector)

```